
CREATE TABLE "PRICES"
(
   PRODUCT_ID INTEGER NOT NULL,
   BRAND_ID INTEGER,
   START_DATE timestamp NOT NULL,
   END_DATE timestamp,
   PRICE_LIST INTEGER NOT NULL,
   PRIORITY char DEFAULT 0,
   PRICE decimal(10,2),
   CURR char(3),
   PRIMARY KEY (PRODUCT_ID, PRICE_LIST)
)
;


